id: agentic_video_director
namespace: company.social.agent

inputs:
  - id: prompt
    type: STRING
    defaults: "A cute robot gardening in a futuristic greenhouse"

tasks:
  - id: enhance_prompt
    type: io.kestra.plugin.ai.agent.AIAgent
    provider:
      type: io.kestra.plugin.ai.provider.GoogleGemini
      modelName: gemini-2.5-flash
      apiKey: "{{ secret('GEMINI_API_KEY') }}"
    systemMessage: |
      You are an expert Social Media Director.
      You must output a VALID JSON object (and nothing else).
      Do not wrap it in markdown code blocks. Just the raw JSON.
      The JSON must have these three keys:
      1. "video_prompt": A concise, visual description for an AI video generator. Focus on motion, lighting, and 9:16 vertical composition.
      2. "caption": An engaging Instagram caption.
      3. "hashtags": A string of 5 relevant hashtags.
    prompt: "Create content for this idea: {{ trigger.body.prompt ?? inputs.prompt }}"

  - id: parse_json
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    beforeCommands:
      - pip install kestra
    script: |
      import json
      from kestra import Kestra

      # Get the raw output from the previous task
      raw_text = """{{ outputs.enhance_prompt.textOutput }}"""

      # Safety cleanup: Remove markdown code blocks if the AI added them
      clean_text = raw_text.replace("```json", "").replace("```", "").strip()

      try:
          data = json.loads(clean_text)
          Kestra.outputs({
              "video_prompt": data.get("video_prompt"),
              "social_caption": data.get("caption"),
              "social_hashtags": data.get("hashtags")
          })
      except Exception as e:
          print(f"Failed to parse JSON: {clean_text}")
          raise e

  - id: generate_video
    type: io.kestra.plugin.gemini.VideoGeneration
    apiKey: "{{ secret('GEMINI_API_KEY') }}"
    model: "veo-3.1-generate-preview"
  
    prompt: "{{ outputs.parse_json.vars.video_prompt }}"
    durationInSeconds: 8
    includeAudio: true

  - id: publish_socials
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    beforeCommands:
      - pip install requests kestra
    env:
      IK_ID: "svh4zwy9a"
      IK_KEY: "{{ secret('IMAGEKIT_PRIVATE_KEY') }}"
      IG_TOKEN: "{{ secret('INSTAGRAM_ACCESS_TOKEN') }}"
      IG_ID: "{{ secret('INSTAGRAM_ACCOUNT_ID') }}"

      CAPTION: "{{ outputs.parse_json.vars.social_caption }}"
      HASHTAGS: "{{ outputs.parse_json.vars.social_hashtags }}"

    inputFiles:
      final_video.mp4: "{{ outputs.generate_video.videoUri }}"

    script: |
      import os
      import requests
      import time

      # --- CONFIG ---
      IK_ID = os.environ["IK_ID"]
      IK_KEY = os.environ["IK_KEY"]
      IG_TOKEN = os.environ["IG_TOKEN"]
      IG_ID = os.environ["IG_ID"]

      # Combine caption and hashtags
      final_caption = f"{os.environ['CAPTION']}\n\n{os.environ['HASHTAGS']}"

      FILE_PATH = "final_video.mp4"

      # --- 1. UPLOAD TO IMAGEKIT ---
      print(f"🚀 Uploading to ImageKit...")
      with open(FILE_PATH, "rb") as f:
          url = "https://upload.imagekit.io/api/v1/files/upload"
          auth = (IK_KEY, "")
          files = {"file": f}
          payload = {
              "fileName": f"ai_reel_{int(time.time())}.mp4",
              "useUniqueFileName": "true",
              "folder": "/ai_generated"
          }
          
          resp = requests.post(url, files=files, data=payload, auth=auth)
          if resp.status_code != 200:
              raise Exception(f"ImageKit Error: {resp.text}")
          
          public_url = resp.json()['url']
          print(f"✅ Video Hosted: {public_url}")

      print("📸 Creating Instagram Container...")

      ig_url = f"https://graph.facebook.com/v19.0/{IG_ID}/media"
      ig_payload = {
          "media_type": "VIDEO",
          "video_url": public_url,
          "caption": final_caption,
          "is_reels": "true",
          "access_token": IG_TOKEN
      }

      ig_req = requests.post(ig_url, params=ig_payload)
      if ig_req.status_code != 200:
          raise Exception(f"IG Create Error: {ig_req.text}")
          
      container_id = ig_req.json()['id']
      print(f"   Container ID: {container_id}")

      print("⏳ Waiting for IG processing...")
      status = "IN_PROGRESS"

      for i in range(50):
          time.sleep(6)
          stat_url = f"https://graph.facebook.com/v19.0/{container_id}"
          stat_resp = requests.get(stat_url, params={
              "fields": "status_code",
              "access_token": IG_TOKEN
          })
          
          if stat_resp.status_code != 200:
              print(f"   ⚠️ API Warning: {stat_resp.text}")
              continue

          status = stat_resp.json().get('status_code', 'UNKNOWN')
          print(f"   Status: {status}")
          
          if status == "FINISHED":
              break
          if status in ["ERROR", "EXPIRED"]:
              raise Exception(f"Instagram processing failed with status: {status}")

      if status == "FINISHED":
          print("🚀 Publishing...")
          pub_url = f"https://graph.facebook.com/v19.0/{IG_ID}/media_publish"
          pub_resp = requests.post(pub_url, params={
              "creation_id": container_id,
              "access_token": IG_TOKEN
          })
          if pub_resp.status_code == 200:
              print(f"🎉 PUBLISHED! ID: {pub_resp.json().get('id')}")
          else:
              raise Exception(f"Publish Error: {pub_resp.text}")
      else:
           raise Exception("Timeout waiting for video processing.")

triggers:
  - id: frontend_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "secret-key-123"

    
errors:
  - id: failure_alert
    type: io.kestra.plugin.core.log.Log
    # 👇 FIXED: Changed 'taskrun.state' to 'execution.state'
    message: "❌ FAILED: {{ execution.state.current }}"
